POST http://localhost:5000/api/auth/register 
Content-Type: application/json

{
    "username": "FarisFer",
  "password": "Itsk21"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "FarisFer",
  "password": "Itsk21"
}

###
GET http://localhost:5000/

###
POST http://localhost:5000/api/auth/register 
Content-Type: application/json

{
  "nama": "string",
  "latitude": 90,
  "longitude": 180,
  "deskripsi": "string",
  "kategori": "string"
}